### ISSUE TITLE
GCP cluster

### ISSUE THREAD

**Issue by nirgn975** [shahargalon/book-store#9]
Create a GKE cluster on GCP. The minimum nodes you can have in a cluster is 3, keep the machines small - you don't need them to be powerful. You don't need any special configuration in the cluster, Google will create 3 Nodes and link them together (to a single network) with VPC for you when you use GKE.

Then, in the `cloudbuild.yaml` file you need to _"apply"_ the kubernetes yaml file so it will create all the components (`deployment`, `service`, `ingress` and `namespace`) in the cluster. And finally make sure you have access to the _"software service"_ we created  in the cloud (get the `{"hello": "world"}` in insomnia).

Call the cluster `prod` (in the future we'll have another one called `dev`.

**Comment by shahargalon** [comment]
I forgot to link it to the right PR,
we solved it
